name: contexto
run-name: Pipeline Contexto

on:
  workflow_dispatch:
   inputs:
     reason:
      description: 'Razones de la Ejecucion'     
      required: true
      default: 'warning'
env:
   actor: ${{github.actor}}
   rama: ${{github.ref}} 
   sha: ${{github.sha}}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Ejecutar Script
        run: python main.py
        
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir Variables
        run: echo 'Actor = {{env.actor}} \n Rama = {{env.ref}} \n SHA = {{env.sha}}'

      - name: Imprimir Entradas
        run: echo 'Razones de Ejecucion = {{input.reason}}'
