# This is a basic workflow to help you get started with Actions

name: Aprendiendo Github Action
run-name: Estoy Aprendiendo Github Action

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ejecutar:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Ejecutar script
        run: python main.py
