name: triggers
run-name: Pipeline Triggers

on:
  push:
    branches: 
      - "aprendiendo-github-actions"
    paths:
      - "**.py"

  workflow_dispatch:
		inputs:
			alerta:
				description : 'Nivel'
				required : true
				default : medio
				type : choice
				option :
				- bajo
				- medio
				- alto

			tags:
				description : 'Opcional'
				required : false
				type : boolean

			enviroment:
				description : 'Objetivo'
				required : true
				type : string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Ejecutar Script
        run: python main.py
