name: triggers
run-name: Pipeline Triggers

on:
  push:
    branches: 
      - "main"
    paths:
      - "**.py" 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Ejecutar Script
        run: python main.py
